language: node_js
git:
  depth: 1
node_js:
- '8'
cache: npm
branches:
  only:
    - /^v\d+\.\d+\.\d+$/
    - master
notifications:
  email: false
install:
  - bash ./scripts/install-dependencies.sh
script:
  - bash ./scripts/deploy.sh
